accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from accounts import views

app_name = 'accounts'

urlpatterns = [
    path('login/',
        auth_views.LoginView.as_view(template_name='accounts/login.html'),
        name='login'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('signup/',views.SignUp.as_view(),name='signup')
]

processproject/urls.py
from django.contrib import admin
from django.urls import path,include
from tasktracker import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.ProjectListView.as_view(),name='home'),
    path('tracker/', include('tasktracker.urls',namespace='tracker')),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('accounts/',include('django.contrib.auth.urls')),
]

tasktracker/urls.py
from django.contrib import admin
from django.urls import path
from tasktracker import views

app_name = 'tasktracker'

urlpatterns=[
    path('processes/<str:pk>/',views.ProjectDetailView.as_view(),name='projectdetail'),
    path('createproject/',views.CreateProjectView.as_view(),name='createproject'),
    path('createtask/',views.CreateTaskView.as_view(),name='createtask'),
    path('click/<str:pk>/',views.ClickRedirectView.as_view(),name='click'),
    path('report/<str:pk>/',views.FullReportView.as_view(),name='report'),
    path('download/<str:pk>/',views.ExcelFileDownload.as_view(),name='download'),
    path('addtime/<int:pk>/',views.AddCustomTimeView.as_view(),name='addtime'),
    path('update/<int:pk>/',views.UpdateTaskView.as_view(),name='updatetask'),
    path('delete/<int:pk>/',views.DeleteTaskView.as_view(),name='deletetask'),
    path('update/<str:pk>/', views.UpdateProjectView.as_view(),name='updateproject'),
    path('delete/<str:pk>/',views.DeleteProjectView.as_view(),name='deleteproject'),
]

tasktracker/models.py
from django.db import models
from datetime import datetime
from django.contrib.postgres.fields import JSONField
import pandas as pd
from django.urls import reverse
from datetime import date,time,timedelta
from tasktracker.functions import convert_to_str,convert_to_timedelta,format_timedelta
from django.contrib.auth import get_user_model

# Create your models here.
User = get_user_model()
class ProjectModel(models.Model):
    #Color choices
    RED = 'red'
    BLUE = 'blue'
    GREEN = 'green'
    ORANGE = 'orange'
    COLOR_CHOICES = [(RED,'Red'),(BLUE,'Blue'),(GREEN,'Green'),(ORANGE,'Orange')]

    user = models.ForeignKey(User,related_name='projects',on_delete=models.CASCADE)
    project = models.CharField(max_length=100, primary_key=True)
    color = models.CharField(max_length=10,choices=COLOR_CHOICES,default=GREEN)
    description = models.CharField(max_length=500,blank=True,null=True)
    dataframe = JSONField(blank=True,null=True)
    #Summaryinformation
    project_total = models.DurationField(blank=True,null=True)
    project_avg = models.DurationField(blank=True,null=True)


    def __str__(self):
        return self.project

    def get_absolute_url(self):
        return reverse('home')

    def print_total(self):
        return format_timedelta(self.project_total)

    def print_avg(self):
        return format_timedelta(self.project_avg)

class TaskModel(models.Model):
    project = models.ForeignKey(ProjectModel,related_name='task',on_delete=models.CASCADE)
    task = models.CharField(max_length=100)
    duration = models.DurationField(blank=True,null=True)
    custom_duration = models.DurationField(blank=True,null=True)
    daily_avg = models.CharField(max_length=100,blank=True,null=True,default=str(timedelta(0)))
    total = models.CharField(max_length=100,blank=True,null=True,default=str(timedelta(0)))
    display_avg = models.CharField(max_length=100,blank=True,null=True)
    display_total = models.CharField(max_length=100,blank=True,null=True)
    dataframe = dataframe = JSONField(blank=True,null=True)

    def __str__(self):
        return self.task

    def get_absolute_url(self):
        task_project = self.project
        obj = ProjectModel.objects.get(project=task_project)
        return reverse('tasktracker:projectdetail', kwargs={'pk':obj.pk})

    def click(self, *args, **kwargs):
        today = date.today()
        if self.dataframe == None:
            #Dataframe has not been created yet
            df = pd.DataFrame(index=[today],data=[self.duration],columns=[self.task])
            self.total = str(df[self.task].sum())
            self.daily_avg = str(df[self.task].sum()/len(df.index))
            #Convert dataframe data to strings before dumping to JSON format
            df = convert_to_str(df,self.task)
            self.dataframe = df.to_json()
            self.save()
        else:
            df = pd.read_json(self.dataframe)
            df = convert_to_timedelta(df,self.task)
            if today in df.index.to_list():
                #Update the row containg todays date
                df.loc[today][self.task] = df.loc[today][self.task]+self.duration
                self.total = str(df[self.task].sum())
                self.daily_avg = str(df[self.task].sum()/len(df.index))
                #Convert dataframe data to strings before dumping to JSON format
                df = convert_to_str(df,self.task)
                self.dataframe = df.to_json()
                self.save()
            else:
                #Create a new row containing todays date
                new_row = pd.DataFrame(index=[today],data=[self.duration],columns=[self.task])
                df=pd.concat([df,new_row])
                self.total = str(df[self.task].sum())
                self.daily_avg = str(df[self.task].sum()/len(df.index))
                df = convert_to_str(df,self.task)
                self.dataframe = df.to_json()
                self.save()

    def add_custom(self, *args, **kwargs):
        today = date.today()
        if self.dataframe == None:
            #Dataframe has not been created yet
            df = pd.DataFrame(index=[today],data=[self.custom_duration],columns=[self.task])
            self.total = str(df[self.task].sum())
            self.daily_avg = str(df[self.task].sum()/len(df.index))
            #Convert dataframe data to strings before dumping to JSON format
            df = convert_to_str(df,self.task)
            self.dataframe = df.to_json()
            self.save()
        else:
            df = pd.read_json(self.dataframe)
            df = convert_to_timedelta(df,self.task)
            if today in df.index.to_list():
                #Update the row containg todays date
                df.loc[today][self.task] = df.loc[today][self.task]+self.custom_duration
                self.total = str(df[self.task].sum())
                self.daily_avg = str(df[self.task].sum()/len(df.index))
                #Convert dataframe data to strings before dumping to JSON format
                df = convert_to_str(df,self.task)
                self.dataframe = df.to_json()
                self.save()
            else:
                #Create a new row containing todays date
                new_row = pd.DataFrame(index=[today],data=[self.custom_duration],columns=[self.task])
                df=pd.concat([df,new_row])
                self.total = str(df[self.task].sum())
                self.daily_avg = str(df[self.task].sum()/len(df.index))
                df = convert_to_str(df,self.task)
                self.dataframe = df.to_json()
                self.save()

tasktracker/forms.py
from django.forms import ModelForm, Textarea
from django import forms
from django.utils.translation import gettext_lazy as _
from tasktracker.models import ProjectModel,TaskModel
from tasktracker.validate import validate_special_char

###### PROJECT MODEL #######
class CreateProjectForm(ModelForm):
    project = forms.CharField(validators=[validate_special_char])
    class Meta:
        model= ProjectModel
        fields =['project','color','description']
        widgets = {
            'description': Textarea(attrs={'cols': 80, 'rows': 3})
        }

###### Task Model #######
class CreateTaskForm(ModelForm):
    class Meta:
        model=TaskModel
        fields = ('project','task','duration')
        labels = {
            'duration': _('Standard time'),
        }
        help_texts = {
            'duration': _('time format: HH:MM:SS'),
            'project': _('Select the project for this task')
        }

    def __init__(self, *args, **kwargs):
        user = kwargs.pop("user", None)
        super().__init__(*args, **kwargs)
        print(user)
        self.fields["project"].queryset = (ProjectModel.objects.all().filter(
                user__exact=user)
            )

class AddCustomTimeForm(ModelForm):
    class Meta:
        model=TaskModel
        fields = ('custom_duration',)
        labels = {
            'custom_duration': _('Time'),
        }
        help_texts = {
            'custom_duration': _('time format: HH:MM:SS. To subtract time use "-" infront. E.g: -00:30:00'),
        }

class UpdateTaskForm(ModelForm):
    class Meta:
        model=TaskModel
        fields = ('task','duration')
        labels = {
            'duration': _('Standard time'),
        }
        help_texts = {
            'duration': _('time format: HH:MM:SS'),
        }

tasktracker/views.py
from django.shortcuts import render
from tasktracker.forms import (CreateProjectForm,AddCustomTimeForm,
    UpdateTaskForm,CreateTaskForm)
from django.urls import reverse,reverse_lazy
from tasktracker.models import ProjectModel,TaskModel
from django.shortcuts import get_object_or_404
from django.views.generic import (TemplateView,ListView,DetailView,UpdateView,
    CreateView,DeleteView,RedirectView)
from tasktracker.functions import (update_total_avgtotal,
    project_dataframe,update_display_text_task)
from tasktracker.chart_functions import retrive_chart_data
from django.contrib.auth.mixins import LoginRequiredMixin
from io import BytesIO as IO
from django.http import HttpResponse
from django.views import View
import pandas as pd


# Create your views here.
class ProjectListView(LoginRequiredMixin,ListView):
    model = ProjectModel
    context_object_name='project'
    template_name='tasktracker/index.html'

    def get_context_data(self, **kwargs):
        context = super(ProjectListView, self).get_context_data(**kwargs)
        User = self.request.user
        projects = User.projects.all()

        context.update({
            'user_projects':projects,
            })
        return context

class ProjectDetailView(LoginRequiredMixin,DetailView):
    model = ProjectModel
    context_object_name = 'project'
    template_name='tasktracker/processes.html'

class FullReportView(LoginRequiredMixin,DetailView):
    model = ProjectModel
    context_object_name = 'project'
    template_name='tasktracker/report.html'

    def get_context_data(self, **kwargs):
        pk = self.kwargs['pk']
        context = super(FullReportView, self).get_context_data(**kwargs)
        project = get_object_or_404(ProjectModel,pk=pk)
        data, labels = retrive_chart_data(project)
        context.update({
            'chart_data':data,
            'chart_labels':labels,
            })
        return context

class ExcelFileDownload(LoginRequiredMixin,DetailView):
    model = ProjectModel
    context_object_name = 'project'
    template_name = 'tasktracker/download.html'

    def get(self, request, *args, **kwargs):
        obj = ProjectModel.objects.get(pk=self.kwargs['pk'])
        excel_file = IO()
        xlwriter = pd.ExcelWriter(excel_file, engine='xlsxwriter')
        df = project_dataframe(obj)
        df.to_excel(xlwriter, "Summary")
        xlwriter.save()
        xlwriter.close()

        excel_file.seek(0)

        response = HttpResponse(excel_file.read(),
                                content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')

        response['Content-Disposition'] = 'attachment; filename="excel_file.xlsx"'
        return response

##############################################
############## CRUD Views#####################
##############################################

############### Project Model ################
class CreateProjectView(LoginRequiredMixin,CreateView):
    form_class= CreateProjectForm
    model = ProjectModel
    template_name = 'tasktracker/crud/projectmodel_form.html'

    def get_absolute_url(self):
        return reverse('home')

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)

class UpdateProjectView(LoginRequiredMixin,UpdateView):
    form_class = CreateProjectForm
    model = ProjectModel
    template_name = 'tasktracker/crud/update_projectmodel.html'

class DeleteProjectView(LoginRequiredMixin,DeleteView):
    model = ProjectModel
    template_name = 'tasktracker/crud/project_confirm_delete.html'
    success_url = reverse_lazy('home')

class ClickRedirectView(LoginRequiredMixin,RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        task = get_object_or_404(TaskModel, pk=kwargs['pk'])
        obj = ProjectModel.objects.get(project=task.project)
        return reverse('tasktracker:projectdetail', kwargs={'pk':obj.pk})

    def get(self, request, *args, **kwargs):
        task = get_object_or_404(TaskModel,pk=self.kwargs.get("pk"))
        task.click()
        proj = task.project
        update_display_text_task(task)
        update_total_avgtotal(proj)
        return super().get(request, *args, **kwargs)

############## Task Model ######################


class CreateTaskView(LoginRequiredMixin,CreateView):
    form_class= CreateTaskForm
    model = TaskModel
    template_name = 'tasktracker/crud/taskmodel_form.html'

    def get_absolute_url(self):
        return reverse('home')

    def get_form_kwargs(self):
        kwargs = super(CreateTaskView, self).get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs

class AddCustomTimeView(LoginRequiredMixin,UpdateView):
    form_class= AddCustomTimeForm
    model = TaskModel
    template_name = 'tasktracker/crud/addtime_form.html'

    def form_valid(self, form):
        self.object = form.save(commit=True)
        self.object.add_custom()
        update_display_text_task(self.object)
        update_total_avgtotal(self.object.project)
        return super().form_valid(form)

class UpdateTaskView(LoginRequiredMixin,UpdateView):
    form_class=UpdateTaskForm
    model = TaskModel
    template_name = 'tasktracker/crud/update_task_form.html'

class DeleteTaskView(LoginRequiredMixin,DeleteView):
    model = TaskModel
    template_name = 'tasktracker/crud/task_confirm_delete.html'
    success_url = reverse_lazy('home')

    def delete(self, *args, **kwargs):
        task = self.get_object()
        proj = task.project
        update_total_avgtotal(proj,task)
        return super(DeleteTaskView, self).delete(*args, **kwargs)

tasktracker/templates/tasktracker/crud/addtime_form.html
{% extends "tasktracker/base.html" %}
{% load bootstrap4 %}

{% block content %}
<br>
<br>
<br>
<div class="container">
  <div class="col-sm text-center customborder">
    <h1>Add custom time to your task:</h1>
  </div>
  <br>
  <br>
  <form method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-success" value="Add">
  </form>
</div>


{% endblock %}

tasktracker/templates/tasktracker/crud/project_confirm_delete.html
{% extends "tasktracker/base.html" %}


{% block content %}
<br>
<br>
<br>
<div class="container">
  <div class="jumbotron">
    <h1>Are you sure you want to delete: {{projectmodel.project}}?</h1>
    <ul>
      <li>All the data associated with {{projectmodel.project}} will be deleted</li>
      <li>It is not possible to reverse this action</li>
    </ul>
  </div>
</div>

<div class="container">
  <form method="post">
    {% csrf_token %}
    <div class="row">
      <div class="col-lg text-left">
        <input type="submit" class="btn btn-danger" value="Confirm delete">
      </div>
      <div class="col-lg text-right">
        <a href="{% url 'tasktracker:projectdetail' pk=projectmodel.pk %}" class="btn btn-success">Go back</a>
      </div>

    </div>
  </form>
</div>


{% endblock %}

tasktracker/templates/tasktracker/crud/projectmodel_form.html
{% extends "tasktracker/base.html" %}
{% load bootstrap4 %}

{% block content %}
<br>
<br>
<br>
<div class="container">
  <div class="col-sm text-center customborder">
    <h1>Create a new project:</h1>
  </div>
  <br>
  <br>
  <form method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-success" value="Submit">
  </form>
</div>


{% endblock %}

tasktracker/templates/tasktracker/crud/task_confirm_delete.html
{% extends "tasktracker/base.html" %}


{% block content %}
<br>
<br>
<br>
<div class="container">
  <div class="jumbotron">
    <h1>Are you sure you want to delete: {{taskmodel.task}}?</h1>
    <ul>
      <li>All the time data associated with {{taskmodel.task}} will be deleted</li>
      <li>It is not possible to reverse this action</li>
    </ul>
  </div>
</div>

<div class="container">
  <form method="post">
    {% csrf_token %}
    <div class="row">
      <div class="col-lg text-left">
        <input type="submit" class="btn btn-danger" value="Confirm delete">
      </div>
      <div class="col-lg text-right">
        <a href="{% url 'tasktracker:projectdetail' pk=taskmodel.project.pk %}" class="btn btn-success">Go back</a>
      </div>

    </div>
  </form>
</div>


{% endblock %}

tasktracker/templates/tasktracker/crud/taskmodel_form.html
{% extends "tasktracker/base.html" %}
{% load bootstrap4 %}

{% block content %}
<br>
<br>
<br>
<div class="container">
  <div class="col-sm text-center customborder">
    <h1>Create a new task:</h1>
  </div>
  <br>
  <br>
  <form method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-success" value="Submit">
  </form>
</div>


{% endblock %}

tasktracker/templates/tasktracker/crud/update_projectmodel.html
{% extends "tasktracker/base.html" %}
{% load bootstrap4 %}

{% block content %}
<br>
<br>
<br>
<div class="container">
  <div class="col-sm text-center customborder">
    <h1>Update your project: </h1>
  </div>
  <br>
  <br>
  <form method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <div class="row">
      <div class="col-sm text-left">
        <input type="submit" class="btn btn-success" value="Change">
      </div>
      <div class="col-sm text-right">
        <a href="{% url 'tasktracker:deleteproject' pk=projectmodel.pk %}" class="btn btn-danger">Delete project</a>
      </div>
    </div>
  </form>
</div>


{% endblock %}

tasktracker/templates/tasktracker/crud/update_task_form.html
{% extends "tasktracker/base.html" %}
{% load bootstrap4 %}

{% block content %}
<br>
<br>
<br>
<div class="container">
  <div class="col-sm text-center customborder">
    <h1>Change your task:</h1>
  </div>
  <br>
  <br>
  <form method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <div class="row">
      <div class="col-sm text-left">
        <input type="submit" class="btn btn-success" value="Change">
      </div>
      <div class="col-sm text-right">
        <a href="{% url 'tasktracker:deletetask' pk=taskmodel.pk %}" class="btn btn-danger">Delete task</a>
      </div>
    </div>
  </form>
</div>


{% endblock %}