accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from accounts import views

app_name = 'accounts'

urlpatterns = [
    path('login/',
        auth_views.LoginView.as_view(template_name='accounts/login.html'),
        name='login'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('signup/',views.SignUp.as_view(),name='signup')
]

processproject/urls.py
from django.contrib import admin
from django.urls import path,include
from tasktracker import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.ProjectListView.as_view(),name='home'),
    path('tracker/', include('tasktracker.urls',namespace='tracker')),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('accounts/',include('django.contrib.auth.urls')),
]

tasktracker/urls.py
from django.contrib import admin
from django.urls import path
from tasktracker import views

app_name = 'tasktracker'

urlpatterns=[
    path('processes/<str:pk>/',views.ProjectDetailView.as_view(),name='projectdetail'),
    path('createproject/',views.CreateProjectView.as_view(),name='createproject'),
    path('createtask/',views.CreateTaskView.as_view(),name='createtask'),
    path('click/<str:pk>/',views.ClickRedirectView.as_view(),name='click'),
    path('report/<str:pk>/',views.FullReportView.as_view(),name='report'),
    path('download/<str:pk>/',views.ExcelFileDownload.as_view(),name='download'),
    path('addtime/<int:pk>/',views.AddCustomTimeView.as_view(),name='addtime'),
    path('update/<int:pk>/',views.UpdateTaskView.as_view(),name='updatetask'),
    path('delete/<int:pk>/',views.DeleteTaskView.as_view(),name='deletetask'),
    path('update/<str:pk>/', views.UpdateProjectView.as_view(),name='updateproject'),
    path('delete/<str:pk>/',views.DeleteProjectView.as_view(),name='deleteproject'),
]

tasktracker/models.py
from django.db import models
from datetime import datetime
from django.contrib.postgres.fields import JSONField
import pandas as pd
from django.urls import reverse
from datetime import date,time,timedelta
from tasktracker.functions import convert_to_str,convert_to_timedelta,format_timedelta
from django.contrib.auth import get_user_model

# Create your models here.
User = get_user_model()
class ProjectModel(models.Model):
    #Color choices
    RED = 'red'
    BLUE = 'blue'
    GREEN = 'green'
    ORANGE = 'orange'
    COLOR_CHOICES = [(RED,'Red'),(BLUE,'Blue'),(GREEN,'Green'),(ORANGE,'Orange')]

    user = models.ForeignKey(User,related_name='projects',on_delete=models.CASCADE)
    project = models.CharField(max_length=100, primary_key=True)
    color = models.CharField(max_length=10,choices=COLOR_CHOICES,default=GREEN)
    description = models.CharField(max_length=500,blank=True,null=True)
    dataframe = JSONField(blank=True,null=True)
    #Summaryinformation
    project_total = models.DurationField(blank=True,null=True)
    project_avg = models.DurationField(blank=True,null=True)


    def __str__(self):
        return self.project

    def get_absolute_url(self):
        return reverse('home')

    def print_total(self):
        return format_timedelta(self.project_total)

    def print_avg(self):
        return format_timedelta(self.project_avg)

class TaskModel(models.Model):
    project = models.ForeignKey(ProjectModel,related_name='task',on_delete=models.CASCADE)
    task = models.CharField(max_length=100)
    duration = models.DurationField(blank=True,null=True)
    custom_duration = models.DurationField(blank=True,null=True)
    daily_avg = models.CharField(max_length=100,blank=True,null=True,default=str(timedelta(0)))
    total = models.CharField(max_length=100,blank=True,null=True,default=str(timedelta(0)))
    display_avg = models.CharField(max_length=100,blank=True,null=True)
    display_total = models.CharField(max_length=100,blank=True,null=True)
    dataframe = dataframe = JSONField(blank=True,null=True)

    def __str__(self):
        return self.task

    def get_absolute_url(self):
        task_project = self.project
        obj = ProjectModel.objects.get(project=task_project)
        return reverse('tasktracker:projectdetail', kwargs={'pk':obj.pk})

    def click(self, *args, **kwargs):
        today = date.today()
        if self.dataframe == None:
            #Dataframe has not been created yet
            df = pd.DataFrame(index=[today],data=[self.duration],columns=[self.task])
            self.total = str(df[self.task].sum())
            self.daily_avg = str(df[self.task].sum()/len(df.index))
            #Convert dataframe data to strings before dumping to JSON format
            df = convert_to_str(df,self.task)
            self.dataframe = df.to_json()
            self.save()
        else:
            df = pd.read_json(self.dataframe)
            df = convert_to_timedelta(df,self.task)
            if today in df.index.to_list():
                #Update the row containg todays date
                df.loc[today][self.task] = df.loc[today][self.task]+self.duration
                self.total = str(df[self.task].sum())
                self.daily_avg = str(df[self.task].sum()/len(df.index))
                #Convert dataframe data to strings before dumping to JSON format
                df = convert_to_str(df,self.task)
                self.dataframe = df.to_json()
                self.save()
            else:
                #Create a new row containing todays date
                new_row = pd.DataFrame(index=[today],data=[self.duration],columns=[self.task])
                df=pd.concat([df,new_row])
                self.total = str(df[self.task].sum())
                self.daily_avg = str(df[self.task].sum()/len(df.index))
                df = convert_to_str(df,self.task)
                self.dataframe = df.to_json()
                self.save()

    def add_custom(self, *args, **kwargs):
        today = date.today()
        if self.dataframe == None:
            #Dataframe has not been created yet
            df = pd.DataFrame(index=[today],data=[self.custom_duration],columns=[self.task])
            self.total = str(df[self.task].sum())
            self.daily_avg = str(df[self.task].sum()/len(df.index))
            #Convert dataframe data to strings before dumping to JSON format
            df = convert_to_str(df,self.task)
            self.dataframe = df.to_json()
            self.save()
        else:
            df = pd.read_json(self.dataframe)
            df = convert_to_timedelta(df,self.task)
            if today in df.index.to_list():
                #Update the row containg todays date
                df.loc[today][self.task] = df.loc[today][self.task]+self.custom_duration
                self.total = str(df[self.task].sum())
                self.daily_avg = str(df[self.task].sum()/len(df.index))
                #Convert dataframe data to strings before dumping to JSON format
                df = convert_to_str(df,self.task)
                self.dataframe = df.to_json()
                self.save()
            else:
                #Create a new row containing todays date
                new_row = pd.DataFrame(index=[today],data=[self.custom_duration],columns=[self.task])
                df=pd.concat([df,new_row])
                self.total = str(df[self.task].sum())
                self.daily_avg = str(df[self.task].sum()/len(df.index))
                df = convert_to_str(df,self.task)
                self.dataframe = df.to_json()
                self.save()

tasktracker/forms.py
from django.forms import ModelForm, Textarea
from django import forms
from django.utils.translation import gettext_lazy as _
from tasktracker.models import ProjectModel,TaskModel
from tasktracker.validate import validate_special_char

###### PROJECT MODEL #######
class CreateProjectForm(ModelForm):
    project = forms.CharField(validators=[validate_special_char])
    class Meta:
        model= ProjectModel
        fields =['project','color','description']
        widgets = {
            'description': Textarea(attrs={'cols': 80, 'rows': 3})
        }

###### Task Model #######
class CreateTaskForm(ModelForm):
    class Meta:
        model=TaskModel
        fields = ('project','task','duration')
        labels = {
            'duration': _('Standard time'),
        }
        help_texts = {
            'duration': _('time format: HH:MM:SS'),
            'project': _('Select the project for this task')
        }

    def __init__(self, *args, **kwargs):
        user = kwargs.pop("user", None)
        super().__init__(*args, **kwargs)
        print(user)
        self.fields["project"].queryset = (ProjectModel.objects.all().filter(
                user__exact=user)
            )

class AddCustomTimeForm(ModelForm):
    class Meta:
        model=TaskModel
        fields = ('custom_duration',)
        labels = {
            'custom_duration': _('Time'),
        }
        help_texts = {
            'custom_duration': _('time format: HH:MM:SS. To subtract time use "-" infront. E.g: -00:30:00'),
        }

class UpdateTaskForm(ModelForm):
    class Meta:
        model=TaskModel
        fields = ('task','duration')
        labels = {
            'duration': _('Standard time'),
        }
        help_texts = {
            'duration': _('time format: HH:MM:SS'),
        }

tasktracker/views.py
from django.shortcuts import render
from tasktracker.forms import (CreateProjectForm,AddCustomTimeForm,
    UpdateTaskForm,CreateTaskForm)
from django.urls import reverse,reverse_lazy
from tasktracker.models import ProjectModel,TaskModel
from django.shortcuts import get_object_or_404
from django.views.generic import (TemplateView,ListView,DetailView,UpdateView,
    CreateView,DeleteView,RedirectView)
from tasktracker.functions import (update_total_avgtotal,
    project_dataframe,update_display_text_task)
from tasktracker.chart_functions import retrive_chart_data
from django.contrib.auth.mixins import LoginRequiredMixin
from io import BytesIO as IO
from django.http import HttpResponse
from django.views import View
import pandas as pd


# Create your views here.
class ProjectListView(LoginRequiredMixin,ListView):
    model = ProjectModel
    context_object_name='project'
    template_name='tasktracker/index.html'

    def get_context_data(self, **kwargs):
        context = super(ProjectListView, self).get_context_data(**kwargs)
        User = self.request.user
        projects = User.projects.all()

        context.update({
            'user_projects':projects,
            })
        return context

class ProjectDetailView(LoginRequiredMixin,DetailView):
    model = ProjectModel
    context_object_name = 'project'
    template_name='tasktracker/processes.html'

class FullReportView(LoginRequiredMixin,DetailView):
    model = ProjectModel
    context_object_name = 'project'
    template_name='tasktracker/report.html'

    def get_context_data(self, **kwargs):
        pk = self.kwargs['pk']
        context = super(FullReportView, self).get_context_data(**kwargs)
        project = get_object_or_404(ProjectModel,pk=pk)
        data, labels = retrive_chart_data(project)
        context.update({
            'chart_data':data,
            'chart_labels':labels,
            })
        return context

class ExcelFileDownload(LoginRequiredMixin,DetailView):
    model = ProjectModel
    context_object_name = 'project'
    template_name = 'tasktracker/download.html'

    def get(self, request, *args, **kwargs):
        obj = ProjectModel.objects.get(pk=self.kwargs['pk'])
        excel_file = IO()
        xlwriter = pd.ExcelWriter(excel_file, engine='xlsxwriter')
        df = project_dataframe(obj)
        df.to_excel(xlwriter, "Summary")
        xlwriter.save()
        xlwriter.close()

        excel_file.seek(0)

        response = HttpResponse(excel_file.read(),
                                content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')

        response['Content-Disposition'] = 'attachment; filename="excel_file.xlsx"'
        return response

##############################################
############## CRUD Views#####################
##############################################

############### Project Model ################
class CreateProjectView(LoginRequiredMixin,CreateView):
    form_class= CreateProjectForm
    model = ProjectModel
    template_name = 'tasktracker/crud/projectmodel_form.html'

    def get_absolute_url(self):
        return reverse('home')

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)

class UpdateProjectView(LoginRequiredMixin,UpdateView):
    form_class = CreateProjectForm
    model = ProjectModel
    template_name = 'tasktracker/crud/update_projectmodel.html'

class DeleteProjectView(LoginRequiredMixin,DeleteView):
    model = ProjectModel
    template_name = 'tasktracker/crud/project_confirm_delete.html'
    success_url = reverse_lazy('home')

class ClickRedirectView(LoginRequiredMixin,RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        task = get_object_or_404(TaskModel, pk=kwargs['pk'])
        obj = ProjectModel.objects.get(project=task.project)
        return reverse('tasktracker:projectdetail', kwargs={'pk':obj.pk})

    def get(self, request, *args, **kwargs):
        task = get_object_or_404(TaskModel,pk=self.kwargs.get("pk"))
        task.click()
        proj = task.project
        update_display_text_task(task)
        update_total_avgtotal(proj)
        return super().get(request, *args, **kwargs)

############## Task Model ######################


class CreateTaskView(LoginRequiredMixin,CreateView):
    form_class= CreateTaskForm
    model = TaskModel
    template_name = 'tasktracker/crud/taskmodel_form.html'

    def get_absolute_url(self):
        return reverse('home')

    def get_form_kwargs(self):
        kwargs = super(CreateTaskView, self).get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs

class AddCustomTimeView(LoginRequiredMixin,UpdateView):
    form_class= AddCustomTimeForm
    model = TaskModel
    template_name = 'tasktracker/crud/addtime_form.html'

    def form_valid(self, form):
        self.object = form.save(commit=True)
        self.object.add_custom()
        update_display_text_task(self.object)
        update_total_avgtotal(self.object.project)
        return super().form_valid(form)

class UpdateTaskView(LoginRequiredMixin,UpdateView):
    form_class=UpdateTaskForm
    model = TaskModel
    template_name = 'tasktracker/crud/update_task_form.html'

class DeleteTaskView(LoginRequiredMixin,DeleteView):
    model = TaskModel
    template_name = 'tasktracker/crud/task_confirm_delete.html'
    success_url = reverse_lazy('home')

    def delete(self, *args, **kwargs):
        task = self.get_object()
        proj = task.project
        update_total_avgtotal(proj,task)
        return super(DeleteTaskView, self).delete(*args, **kwargs)

tasktracker/templates/tasktracker/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Project tracker</title>

    {# CDN's #}
    {# Jquary and poppers #}
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>

    {# Bootstrap 4 #}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    {# Chart script #}
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>

    <!-- For icons-->
    <script src="https://kit.fontawesome.com/9bc89fa1dd.js" crossorigin="anonymous"></script>

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/custom.css'%}">
  </head>

  <body>
  <div id="page-container">
    <!-- NAVBAR -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" style="height:50px;">
      <a class="navbar-brand text-white" href="{% url 'home' %} " style="margin-left:20px;">Project timer (BETA) <i class="fas fa-laptop-code" style="color:#16a9a9;margin-left:10px;"></i></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        {% if user.is_authenticated %}
        <ul class="navbar-nav">

        </ul>
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a href="#" class="nav-link text-white">{{user.username}} <i class="fas fa-user-tie"></i></a>
          </li>
          <li class="nav-item">
            <a href="{% url 'accounts:logout' %}" class="nav-link text-white">Log Out</a>
          </li>
        </ul>
          {% else %}
        <ul class="navbar-nav ml-auto">
          <li class="nav-item" style="margin-right: 10px;">
            <a href="{% url 'accounts:signup' %}" class="btn btn-light btn-md" >Sign up</a>
          </li>
          <li class="nav-item">
            <a href="{% url 'accounts:login' %}" class="btn btn-light btn-md" >Log in</a>
          </li>
        </ul>
          {% endif %}
      </div>
    </nav>

    <div id="content-wrap">

    {% block content %}
    {% endblock %}

    </div>
    <!-- Footer-->
    <footer class="footer" id="footer" >
      <div class="container-fluid text-center custom-background">
      <div class="row extra-padding">
        <div class="col-sm-4">
          <h3 class="text-white"><i class="fas fa-address-book"></i> Contact Us:</h3>
          <br>
          <a href ="mailto: mariusgronli@gmail.com" class="text-white">mariusgronli@gmail.com</a>
          <h5 class="text-white">+4793442066</h5>
        </div>
        <div class="col-sm-4">
          <h3 class="text-white"><i class="fas fa-thumbtack"></i> Location:</h3>
          <br>
          <h5 class="text-white">Rua neves de sousa 22</h5>
          <h5 class="text-white">Oeiras, Portugal</h5>
        </div>
        <div class="col-sm-4">
          <h3 class="text-white"><i class="fas fa-link"></i> Useful links:</h3>
          <br>
          <h5 class="text-white">Login</h5>
          <h5 class="text-white">Register</h5>
        </div>
      </div>
    </div>
  </footer>
</div>
</body>
</html>

tasktracker/templates/tasktracker/download.html
{% extends "tasktracker/base.html" %}
{% load static %}

{% block content %}

<br>
<br>
<br>

<div class="container">
  <div class="col-sm">
    <h1>The full time entry for your project is downloaded</h1>
  </div>
</div>


{% endblock %}

tasktracker/templates/tasktracker/index.html
{% extends "tasktracker/base.html" %}
{% load static %}

{% block content %}

  <div class="container" style="margin-top:80px;">
  </div>

  <div class="col-lg text-center">
    <h1>Track how much time you spend on each project</h1>
    <p class="lead">Select your project and start tracking! </p>
  </div>

  <br>
  <br>

  <div class="container-countries" style="margin-left:20%;margin-right:20%;">
  {% for proj in user_projects %}
    {% if proj.color == 'red' %}
    <div class="row">
        <div class="col-lg">
          <a href="{% url 'tasktracker:projectdetail' pk=proj.pk %}" class="btn btn-block btn-danger">{{proj.project}}</a>
        </div>
    </div>
    <br>
    {% elif proj.color == 'blue' %}
    <div class="row">
        <div class="col-lg">
          <a href="{% url 'tasktracker:projectdetail' pk=proj.pk %}" class="btn btn-block btn-info">{{proj.project}}</a>
        </div>
    </div>
    <br>
    {% elif proj.color == 'green' %}
    <div class="row">
        <div class="col-lg">
          <a href="{% url 'tasktracker:projectdetail' pk=proj.pk %}" class="btn btn-block btn-success">{{proj.project}}</a>
        </div>
    </div>
    <br>
    {% elif proj.color == 'orange' %}
    <div class="row">
        <div class="col-lg">
          <a href="{% url 'tasktracker:projectdetail' pk=proj.pk %}" class="btn btn-block btn-warning text-white">{{proj.project}}</a>
        </div>
    </div>
    <br>

    <br>
    {% endif %}<!-- To give spesific color for each country -->
  {% endfor %}<!--End iteration over project model-->

    <hr>

  <div class="col-lg text-center">
    <a href="{% url 'tasktracker:createproject' %} " class="btn btn-dark">Add a new project</a>
  </div>

</div> <!--end background-->



{% endblock %}

tasktracker/templates/tasktracker/processes.html
{% extends "tasktracker/base.html" %}
{% load static %}


{% block content %}

<div class="backgroundimg">
  <br>
  <br>
  <br>
<div class="container">
  <div class="jumbotron text-center">
    <h1>Tracker for {{project.project}}! <a
      href="{% url 'tasktracker:updateproject' pk=project.pk %} "><i
      class="fas fa-edit" id="editproj"></i></a></h1>
    <hr>
    <p class="lead">{{project.description}}</p>
  <div class="col-lg text-center">
    <a href="{% url 'tasktracker:report' pk=project.pk %}" class="btn btn-lg btn-info">See full report</a>
  </div>
  </div>
</div>

  <br>
  <br>

  <div class="container">
    <div class="jumbotron">
    <table class="table table-hover">
      <thead>
        <th>Task</th>
        <th>Daily time</th>
        <th>Total time</th>
        <th>Time</th>
        <th>Custom time</th>
      </thead>
      <tbody>
        {% for task in project.task.all  %}
        <tr>
          <th>{{task.task}}</th>
          <td>{{task.display_avg}}</td>
          <td>{{task.display_total}}</td>
          <td><a href="{% url 'tasktracker:click' pk=task.pk %}" class="btn btn-small btn-light">+</a></td>
          <td><a href="{% url 'tasktracker:addtime' pk=task.pk %}" class="btn btn-small btn-light">Add/Sub</a></td>
          <td><a href="{% url 'tasktracker:updatetask' pk=task.pk %}" class="btn btn-small btn-info">Edit</a></td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    <br>
    <hr>
    <div class="col-lg text-center">
      <a href="{% url 'tasktracker:createtask' %}" class="btn btn-lg btn-dark">New task</a>
    </div>
  </div>
  </div>

  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>

</div> <!-- end background img -->

{% endblock %}

tasktracker/templates/tasktracker/report.html
{% extends "tasktracker/base.html" %}
{% load static %}


{% block content %}
<br>
<br>
<br>

<div class="container">
  <div class="row">
    <div class="col-sm text-center">
      <h1 class="customborder">{{project.project}}</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-sm text-center">
      <p class="lead">{{project.description}}</p>
    </div>
  </div>
</div>

<br>
<br>

<div class="container">
  <div class="row">
    <div class="col-sm-5">
      <div class="row">
        <div class="col-sm">
          <h4 class="customborder2" style="padding-bottom:2px;"><i class="fas fa-user-clock" style="color:#1bca79;"></i> Total time spent on project:</h4>
        </div>
      </div>
      <div class="row">
        <div class="col-sm">
          <h3>{{project.print_total}}</h3>
        </div>
      </div>
    </div>
    <div class="col-sm-2">

    </div>
    <div class="col-sm-5">
      <div class="row">
        <div class="col-sm">
          <h4 class="customborder2" style="padding-bottom:2px;"><i class="fas fa-stopwatch" style="color:#2ba72f;"></i> Average daily time spent on project:</h4>
        </div>
      </div>
      <div class="row">
        <div class="col-sm">
          <h3>{{project.print_avg}}</h3>
        </div>
      </div>
    </div>
  </div>
</div>

<br>
<br>

<div class="container">
  <div class="row">
    <div class="col-sm">
      <canvas id="myChart" width="400" height="200"></canvas>
    </div>
  </div>
  <br>
  <br>
  <br>
  <div class="row">
    <div class="col-sm text-center">
      <a href="{% url 'tasktracker:download' pk=project.pk %}" class="btn btn-success btn-lg">To Excel</a>
    </div>
  </div>
</div>

<br>
<br>
<br>



<script>
var ctx = document.getElementById('myChart').getContext('2d');
var myChart = new Chart(ctx, {
    type: 'bar',
    data: {
        labels: {{chart_labels|safe}},
        datasets: [{
            label: '# Time spent on different task in the project',
            data: {{chart_data|safe}},
            backgroundColor: [
                'rgba(255, 99, 132, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(255, 206, 86, 0.2)',
                'rgba(75, 192, 192, 0.2)',
                'rgba(153, 102, 255, 0.2)',
                'rgba(255, 159, 64, 0.2)'
            ],
            borderColor: [
                'rgba(255, 99, 132, 1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(255, 159, 64, 1)'
            ],
            borderWidth: 1
        }]
    },
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero: true
                }
            }]
        }
    }
});
</script>
{%endblock%}